### ISSUE TITLE
Documentation: how to call hooks

### ISSUE THREAD

**Issue by ari** [freebsd/poudriere#970]
https://github.com/freebsd/poudriere/wiki/hooks

This page suggests that the top that the hook file should be named HOOKNAME.sh when in fact it should be lowercase.

Also, it does not explain that the event is sent as the first parameter ($1) to the script. Perhaps an example would make everything clear.

**Comment by ari** [comment]
Also it should be noted that putting

```
#!/usr/local/bin/bash
```

at the top of the hook doesn't cause it to be run by bash. poudriere isn't running the hook as an executable but rather hardcoding it to run only from sh.

**Comment by michael-o** [comment]
@bdrewery This documentation flaw still holds true.

**Comment by bdrewery** [comment]
Fixed these.

**Comment by michael-o** [comment]
@bdrewery It is still not correct. The hook has to be a POSIX shell script since `/bin/sh` is used as interpreter. Moreover the args depicted in the wiki are wrong.

```
/bin/sh "${hookfile:?}" "${event}" "$@"
```

**Comment by bdrewery** [comment]
> [@bdrewery](https://github.com/bdrewery) It is still not correct. The hook has to be a POSIX shell script since `/bin/sh` is used as interpreter. 

I don't see the problem you're pointing at. It says `/bin/sh` is used, that implies it must adhere to `/bin/sh` standards.

> Moreover the args depicted in the wiki are wrong.
> 
> ```
> /bin/sh "${hookfile:?}" "${event}" "$@"
> ```

Fixed that.

If I could give you access to the wiki I would. I don't have control over that. Maybe @bapt can.

**Comment by bapt** [comment]
@bdrewery  your are now maintainer of the repo, don't known why you were not before and @michael-o  is now member of the poudriere team so he should be able to edit the wiki

**Comment by michael-o** [comment]
I have updated the docs accordingly.
